services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\ConferenceRoom\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.conference_room.pre_persist, priority: 10 }
