services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## post_persist
  ##################################
  Ivoz\Domain\Service\FaxesInOut\SendFaxFile:
    tags:
      - { name: ivoz.lifecycle.faxes_in_out.post_persist, priority: 10}
