services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Fax\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.fax.pre_persist, priority: 10}
