Ivoz\Domain\Model\Friend\Friend:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\FriendDoctrineRepository
  type: entity
  table: Friends
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    psEndpoints:
      targetEntity: Ast\Domain\Model\PsEndpoint\PsEndpointInterface
      mappedBy: friend
    patterns:
      targetEntity: Ivoz\Domain\Model\FriendsPattern\FriendsPatternInterface
      mappedBy: friend
  lifecycleCallbacks: {  }
