Ivoz\Domain\Model\HuntGroup\HuntGroup:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\HuntGroupDoctrineRepository
  type: entity
  table: HuntGroups
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    huntGroupsRelUsers:
      targetEntity: Ivoz\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUserInterface
      mappedBy: huntGroup
  lifecycleCallbacks: {  }
