Ivoz\Domain\Model\OutgoingDDIRule\OutgoingDDIRuleAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
    OutgoingDDIRules_ibfk_2:
      columns:
        - forcedDDIId
  uniqueConstraints:
    ruleName:
      columns:
        - companyId
        - name
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    defaultAction:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
        comment: '[enum:keep|force]'
      column: defaultAction
  manyToOne:
    company:
      targetEntity: Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
      orphanRemoval: false
    forcedDDI:
      targetEntity: Ivoz\Domain\Model\DDI\DDIInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        forcedDDIId:
          referencedColumnName: id
      orphanRemoval: false
