<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\AccCdr\AccCdrRepository;

/**
 * AccCdrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccCdrDoctrineRepository extends EntityRepository implements AccCdrRepository
{

    public function fetchTarificableList(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $criteria += [
            Criteria::expr()->neq('peeringContract' , null),
            Criteria::expr()->neq('peeringContract' , '')
        ];

        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }
}
