services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Company\SanitizeEmptyValues:
    tags:
      - { name: ivoz.lifecycle.company.pre_persist, priority: 10 }

  Ivoz\Domain\Service\CallACLPattern\PropagateBrandGenericCallACLPatterns:
    tags:
      - { name: ivoz.lifecycle.company.pre_persist, priority: 20 }

  ##################################
  ## post_persist
  ##################################
  Ivoz\Domain\Service\Domain\UpdateByCompany:
    tags:
      - { name: ivoz.lifecycle.company.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $domainRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\Domain\\Domain")'

  Kam\Domain\Service\UsersDomainAttr\CreateByCompany:
    tags:
      - { name: ivoz.lifecycle.company.post_persist, priority: 20 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Ivoz\Domain\Service\CompanyService\PropagateBrandServices:
    tags:
      - { name: ivoz.lifecycle.company.post_persist, priority: 30 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $brandServiceRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\BrandService\\BrandService")'

  # services with priority 40 & 41 & 42 in lifecycle/xml_rpc.yml