<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\MusicOnHold\MusicOnHoldRepository;

/**
 * OutgoingDDIRulesPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoingDDIRulesPatternDoctrineRepository extends EntityRepository implements MusicOnHoldRepository
{
}
