services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Core\Infrastructure\Service\Asterisk\ARI\ARIConnector:
    arguments:
      $applicationServerRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\ApplicationServer\\ApplicationServer")'
      $userName: '%ari_user%'
      $password: '%ari_password%'
      $port: '%ari_port%'
